export const copy = {
  product: 'RngKit',
  skipToMain: 'Skip to main content',
  destinations: {
    collect: 'Collect',
    reports: 'Reports',
    combine: 'Combine',
    help: 'Help',
  },
  primaryNav: 'Primary',
  theme: {
    legend: 'Theme',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
  },
  fold: {
    label: 'Fold',
    raw: '0 - Raw',
  },
  sampleBits: 'Sample size (bits)',
  sampleInterval: 'Sample interval (seconds)',
  outputRoot: 'Output folder',
  noOutputFolder: 'No output folder selected. Choose a folder to continue.',
  entropySource: 'Entropy source',
  refreshSources: 'Refresh sources',
  chooseFolder: 'Choose folder',
  openWorkingFolder: 'Open working folder',
  start: 'Start',
  stop: 'Stop',
  startAnother: 'Start another session',
  openSessionFolder: 'Open session folder',
  chooseReportInput: 'Choose input',
  generateReport: 'Generate report',
  openReport: 'Open report',
  openContainingFolder: 'Open containing folder',
  replaceTitle: 'Replace existing report?',
  replaceBody:
    'An XLSX file already exists for this input. Cancel keeps it. Replace is an explicit second request.',
  cancel: 'Cancel',
  replace: 'Replace',
  chooseCsvInputs: 'Add files',
  clearCombineInputs: 'Clear all',
  removeCombineInput: 'Remove',
  createDerived: 'Create derived bundle',
  generateXlsx: 'Generate XLSX',
  openFolder: 'Open folder',
  outcome: {
    dismiss: 'Dismiss',
    actionErrorTitle: 'Action could not be completed',
    openSessionFolder: 'Open session folder',
    openReport: 'Open report',
    openReportFolder: 'Open report folder',
    openDerivedFolder: 'Open derived folder',
    openCollectionWorkingFolder: 'Open Collect working folder',
    openReportWorkingFolder: 'Open Reports working folder',
    openCombineWorkingFolder: 'Open Combine working folder',
  },
  chart: {
    title: 'Descriptive cumulative Z',
    boundary: 'Z shows balance over time; it does not certify randomness.',
    xAxis: 'Sample index',
    yAxis: 'Descriptive cumulative Z',
    series: 'Descriptive cumulative Z',
    zero: 'Zero',
    refPlus: 'Reference +1.96',
    refMinus: 'Reference -1.96',
    fitAll: 'Fit all',
    empty:
      'No committed samples yet. Every committed point is retained for this session.',
    caption:
      'Sample index versus descriptive cumulative Z. The zero line and ±1.96 lines are visual guides only.',
    retainedPoints: 'Retained points',
    following: 'Following new samples',
    paused: 'View paused; new samples still append',
  },
  close: {
    title: 'Stop collection before closing?',
    body: 'The session is still collecting. Stop and exit waits for the recording to finish, then closes the window. Keep collecting cancels the close.',
    keep: 'Keep collecting',
    stopAndExit: 'Stop and exit',
    finalizingTitle: 'Finishing the session',
    finalizingBody:
      'The session is stopping. The window will close after the recording is finalized. Closing again does not force quit.',
    finalizingReason: 'The window will close after finalization.',
  },
  errors: {
    copyDiagnostics: 'Copy diagnostics',
    copied: 'Diagnostics copied',
    copyFailed: 'Diagnostics could not be copied.',
    empty: 'No diagnostics are available.',
  },
  noSources:
    'Sources are discovered automatically on startup. Refresh to search again. Nothing is selected automatically.',
  noReportInput: 'No report input selected.',
  noCombineInputs: 'No CSV files selected.',
  status: 'Status',
} as const;

export const FOLD_OPTIONS = [
  { value: 0, label: copy.fold.raw },
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
] as const;
